try {
  console.log(myFunctions());
} catch (e) {
    console.log(e.message);
}

